### ISSUE TITLE
[question] Voxel-wise mask recommendation for whole brain analysis

### ISSUE THREAD

**Issue by smeisler** [NotaCS/Functionnectome#5]
Hi,

I am planning on running a whole brain voxel-based analysis of Functionnectome outputs; should I use the whole-brain mask, or a gray-matter mask? Would using a whole-brain mask lead to redundancy and longer running times, or would I be missing something important by restricting only to gray-matter?

Thanks,
Steven

EDIT: see in the manual that it should be gray matter

**Comment by NotaCS** [comment]
Hi Steven,

Yes, as you saw, we recommend using a grey matter mask.
Indeed, it defines what kind of signal is projected onto the white matter, so if you use the whole brain, you'll get the white matter BOLD signal used there. Although there are some works exploring this white matter signal, it's much noisier than the grey matter's so we prefer not to keep it.

Cheers,
Victor
