### ISSUE TITLE
Cannot download WhiteRest atlas and RSN labels information

### ISSUE THREAD

**Issue by m-petersen** [NotaCS/Functionnectome#6]
Hi Victor,

the download of the atlas and RSN label information from the link (https://www.dropbox.com/s/mo4zs159rqhqopv/WhiteRest.zip?dl=0) does not work from my computers.

Best,
Marvin

**Comment by NotaCS** [comment]
Hi Marvin,

Mmmmh, that's weird. It works fine on my end, even when I try it in a private window on my browser.
Can you tell me in more detail what is not working?
Have you tried a different browser? (it may be a compatibility issue between dropbox and your browser)

Cheers,
Victor

**Comment by m-petersen** [comment]
Ah indeed. I used Firefox initially. Using Chrome worked fine. Thanks for the swift reply!

**Comment by NotaCS** [comment]
You're welcome!
Have a great day,
Victor
